// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
////// // ...
 ///await Firebase.initializeApp(
   ///options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLl7eEROYgT7Xqz-3cU8VZCN5U0xw3Q38',
    appId: '1:507283736563:web:0d3f74adedf378a4423486',
    messagingSenderId: '507283736563',
    projectId: 'auth-68455',
    authDomain: 'auth-68455.firebaseapp.com',
    databaseURL: 'https://auth-68455-default-rtdb.firebaseio.com',
    storageBucket: 'auth-68455.appspot.com',
    measurementId: 'G-24ZJK0G3B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDGJalmQ4P31edLt-rtb5BPdEV8PBLy4',
    appId: '1:507283736563:android:ee4d07fa64bfb0c3423486',
    messagingSenderId: '507283736563',
    projectId: 'auth-68455',
    databaseURL: 'https://auth-68455-default-rtdb.firebaseio.com',
    storageBucket: 'auth-68455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8_UCoQAFrdhRqocr7eoHJy9CoQt1UeY',
    appId: '1:507283736563:ios:84efaf19ea6868b5423486',
    messagingSenderId: '507283736563',
    projectId: 'auth-68455',
    databaseURL: 'https://auth-68455-default-rtdb.firebaseio.com',
    storageBucket: 'auth-68455.appspot.com',
    iosClientId: '507283736563-6f3t9b3qvf1g0c57ginmpsn5eto7f7g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.preciousGifts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8_UCoQAFrdhRqocr7eoHJy9CoQt1UeY',
    appId: '1:507283736563:ios:84efaf19ea6868b5423486',
    messagingSenderId: '507283736563',
    projectId: 'auth-68455',
    databaseURL: 'https://auth-68455-default-rtdb.firebaseio.com',
    storageBucket: 'auth-68455.appspot.com',
    iosClientId: '507283736563-6f3t9b3qvf1g0c57ginmpsn5eto7f7g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.preciousGifts',
  );
}
